version: "3.6"

services:
  pg_chainlink:
    image: postgres:14.2
    container_name: pg_chainlink
    volumes:
      - ~/.chainlink-rinkeby:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PW}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432

  chainlink:
    image: smartcontract/chainlink:1.4.1-root
    container_name: chainlink-rinkeby
    command: ["local","n","-p","/chainlink/.password","-a","/chainlink/.api"]
    volumes:
      - ~/.chainlink:/chainlink/
    restart: always
    depends_on:
      - pg_chainlink
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      ETH_CHAIN_ID: ${ETH_CHAIN_ID}
      ETH_URL: ${ETH_URL}
      ETH_HTTP_URL: ${ETH_HTTP_URL}
      DATABASE_URL: postgresql://${DB_USER}:${DB_PW}@pg_chainlink:5432/${DB_NAME}?sslmode=disable
      MIN_OUTGOING_CONFIRMATIONS: "${MIN_OUTGOING_CONFIRMATIONS}"
      LINK_CONTRACT_ADDRESS: "${LINK_CONTRACT_ADDRESS}"
      CHAINLINK_TLS_PORT: "${CHAINLINK_TLS_PORT}"
      SECURE_COOKIES: "${SECURE_COOKIES}"
      GAS_UPDATER_ENABLED: "${GAS_UPDATER_ENABLED}"
      ALLOW_ORIGINS: "${ALLOW_ORIGINS}"
    ports:
      - 6688:6688
    expose:
      - "6688"

volumes:
  .chainlink-rinkeby:
  .chainlink:
